<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Spring Boot Email using FreeMarker</title>
</head>
<body>
<div style="margin-top: 10px">Greetings</div>
    <p>This is your otp</p>
    <p>${authUserOtp}</p>OTP will expire in 1 minutes.
    <p>Thank you</p>
</div>
<br/>
<div> Regards, Felix Phan</div>
</body>
</html>