spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bib
    username: postgres
    password: tung123
    show-sql: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    user:
      name: bib
      password: 123456
  mail:
    host: smtp.gmail.com
    port: 587
    username: tungcsp221199@gmail.com
    password: yreitgydtplzkfcw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  error:
    include-message: always